### ISSUE TITLE
PBR not working in Safari >= 15.1 on M1 GPUs

### ISSUE THREAD

**Issue by superdump** [bevyengine/bevy#3574]
## Bevy version

`main` or >= 0.6

## Operating system & version

macOS 12.1

## What you did

Run any PBR bevy app in wasm on Safari >= 15.1 on an M1 mac.

## What you expected to happen

App renders correctly in the Safari tab.

## What actually happened

Safari tab hangs.

## Additional information

This was narrowed down to being because of dynamically indexing into fixed-size arrays in uniform buffers. This is done as part of the clustered-forward rendering.

Disabling "WebGL via Metal" allows the app to render correctly.

This seems to be a bug somewhere in Safari / WebKit / ANGLE / Metal / M1 drivers. A bug was filed here: https://bugs.webkit.org/show_bug.cgi?id=234926

**Comment by tqwewe** [comment]
Compiling a 3D scene and running in safari seems to fail for me also, and I am on 2019 Intel mac.

**Comment by superdump** [comment]
On the WebKit bug tracker it was noted that it's possible that the binding becomes too large after some intermediate processing. I tried reducing the binding sizes to 16000 bytes and even 8000 bytes to test the theory. It did not help, still broken, the tab still hangs and never manages to draw a single frame.

**Comment by Rust-Ninja-Sabi** [comment]
Same issue on Mac m1. 

Any news ?

**Comment by ostwilkens** [comment]
This is the error I get on both iOS and MacOS safari:
`WebGL: INVALID_ENUM: framebufferTexture2D: invalid attachment`

**Comment by gilescope** [comment]
I get "Unable to create shader object" when I try on iOS's safari on bevy 0.8. Would be nice to be able to get iOS working as there's no alternatives thanks to apple's one browser policy. (The good news is that android seems to work.) That said safari on mac isn't much better - I can get it to make the screen outside of the browser go crazy colors so apple clearly have got some bugs that should not ever happen.

**Comment by jinleili** [comment]
Running pbr example on my M1 Mac looks fine. Safari version 15.6.1, enabled `WebGL 2.0`, disabled `WebGL via Metal`
<img width="1204" alt="截屏2022-08-25 09 20 34" src="https://user-images.githubusercontent.com/1001342/186553408-46209e75-a0e0-4b61-a4dc-ac9224e9554f.png">

**Comment by superdump** [comment]
@jinleili yeah, this was a regression introduced when they switched to using ANGLE as their backend to support WebGL2 via Metal. But we cannot expect users of web pages to enable developer options and change that setting. It has to work in Safari with its default configuration.

**Comment by Rust-Ninja-Sabi** [comment]
Disable WebGL via Metal makes it very slow.

Is there a way to do this in a bevy application?

**Comment by bjorn3** [comment]
Pretty sure that is not possible. This kind of internal browser preferences are normally not writeable by web pages.

**Comment by maxammann** [comment]
I haven't yet been able to avoid the error `INVALID_ENUM: framebuffertexture2d invalid attachment` by disabling Metal for WebGL in Safari (Desktop and iPad). I'm working on that issue: https://github.com/maplibre/maplibre-rs/issues/164

I do not dynamically index into uniforms in my shaders, but I dynamically index into a variable:

```
    var VERTICES: array<vec3<f32>, 6> = array<vec3<f32>, 6>(
        vec3<f32>(0.0, 0.0, z),
        vec3<f32>(0.0, EXTENT, z),
        vec3<f32>(EXTENT, 0.0, z),
        vec3<f32>(EXTENT, 0.0, z),
        vec3<f32>(0.0, EXTENT, z),
        vec3<f32>(EXTENT, EXTENT, z)
    );
    let a_position = VERTICES[vertex_idx];

```

**Comment by maxammann** [comment]
This should be resolved with iOS 16 and Safari 16.

**Comment by mockersf** [comment]
PBR shader is still broken on Safari 16

**Comment by maxammann** [comment]
Yes, sorry it seems like my problem is unrelated. Also just tested Safari Technology Preview (Release 154). Still the same problem with the PBR example.

**Comment by Konard** [comment]
> This should be resolved with iOS 16 and Safari 16.

It still does not work for the 3D examples on the Bevy website on iPadOS 16 (iPad Pro with M1).

**Comment by rozgo** [comment]
In Safari Technology Preview Release 162, there seems to be no more rendering errors, but PBR materials dont render.

**Comment by rrohrer** [comment]
Since this has gone so long without a fix from Apple would it make sense for bevy to implement a workaround?

I don’t have a ton of experience with the engine but I’d be willing to look into it if there’s appetite. 3D not working in safari is a deal breaker for me 🫠

**Comment by gilescope** [comment]
EU is hopefully implementing a fix of forcing apple to ship chrome and
Firefox on iOS.

**Comment by mockersf** [comment]
It seems it's fixed on the latest Safari Technical Preview 🎉 

![Screenshot 2023-03-04 at 00 08 19](https://user-images.githubusercontent.com/8672791/222852293-3d5e03e3-8a88-4dba-b627-d2ff9818b259.png)

**Comment by rrohrer** [comment]
Amazing!

**Comment by mockersf** [comment]
this is now fixed with today iOS / macOS release for me 🎉

**Comment by superdump** [comment]
Same for me on macOS 13.3 with Safari Version 16.4 (18615.1.26.11.22) on M1 Max. Yey! Closing...
