### ISSUE TITLE
Adding Entity as child to other entity makes it invisible

### ISSUE THREAD

**Issue by ashirviskas** [bevyengine/bevy#5081]
## Bevy version

`0.7.0`

## \[Optional\] Relevant system information
OS: Arch Linux
Cargo version: `cargo 1.63.0-nightly`

```ignore
2022-06-23T15:29:27.512314Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD RADV RENOIR", vendor: 4098, device: 5708, device_type: IntegratedGpu, backend: Vulkan }
```

## What you did

I tried adding new entities as children to parent entity.

## What went wrong

Child entities are invisible, but they still function (as colliders for example).

## Additional information

Code that works and renders all entities (only included shortened version for the left wall, but code does the same for all of the walls):

``` rust
let cell_wall_entity_left = commands
    .spawn()
    .insert_bundle(
        SpriteBundle {
            sprite: Sprite {
                color: Color::rgb(0.5, 0.5, 0.3),
                ..default()
            },
            transform: Transform {
                translation: wall_position.extend(0.1),
                scale: Vec3::new(40., 5. , 1.),
                ..default()
            },
            ..default()
        },
    )
    .insert(Collider)
    .id();
let parent_cell = commands
    .spawn_bundle(CellBundle::new(
        SpriteBundle {
            sprite: Sprite {
                color: cell_type.to_color(),
                ..default()
            },
            transform: Transform {
                translation: cell_position.extend(0.),
                scale: Vec3::new(CELL_SIZE.x, CELL_SIZE.y, 1.0),
                ..default()
            },
            ..default()
        },
        Cell::new(),
        Collider,
    ));
```

![image](https://user-images.githubusercontent.com/11985242/175338480-394fc35a-c7df-4167-a190-8922f7daeb25.png)

If I change the last line to:

```rust
    )).insert(CellType::Cell).push_children(&[cell_wall_entity_left]);
```

Then it looks like this: 
![image](https://user-images.githubusercontent.com/11985242/175339193-0d99b966-0378-4955-a7be-50c4a0c1391f.png)

**Comment by DJMcNab** [comment]
Are you sure it's invisible and not just outside the screen boundaries?

You have requested for the wall to be placed at `(CELL_SIZE.x*wall_position.x, CELL_SIZE.y*wall_position.y)`. I would be surprised if that is within the screenshot area you have given, given its small size.

**Comment by ashirviskas** [comment]
>The bug here is actually the collider still being in that spot. I believe this is a known issue with bevy_rapier.

Oh, that might explain it. Any issue I could track?

**Comment by devil-ira** [comment]
Hmm. Looks like this issue should be fixed in version 0.14 of `bevy_rapier` https://github.com/dimforge/bevy_rapier/issues/172

**Comment by ashirviskas** [comment]
[*My cell wall spawning code*](https://github.com/ashirviskas/VirusGameRust/blob/main/src/main.rs#L621) and [*Cell spawning code + adding cell walls as children*](https://github.com/ashirviskas/VirusGameRust/blob/main/src/main.rs#L581) that does not work as intended. I can now see the walls being rendered properly, but their collider boxes are in the middle of the world and you can see the particles bouncing off of them:

https://user-images.githubusercontent.com/11985242/175356850-d0b12e67-bf82-47e0-9322-7d64c57c4d9f.mp4

**Comment by devil-ira** [comment]
Try using the debug-render feature of bevy_rapier2d and fiddle with your code a bit. Can't help much as I'm on my phone right now.

**Comment by ashirviskas** [comment]
>Try using the debug-render feature of bevy_rapier2d and fiddle with your code a bit. Can't help much as I'm on my phone right now.

Thanks for the tips! I enabled debug-render, and refactored child spawning several times, but still no go. It either messes up the `Sprite` or the `Collider` position. Can't have both it seems
