### ISSUE TITLE
Inputs can be missed (or duplicated) when using a fixed time step

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#6183]
## Bevy version

0.8.1

## What you did

Create a system that responds to input events inside of a fixed times step.

## What went wrong

Sometimes, input events are missed: `Input::just_pressed` and `just_released` are never picked up.

Other times, they're duplicated: we respond to the same input multiple times.

### Missed inputs

Fixed time step systems may not run every frame, but `Input::just_pressed` and friends is reset every frame (and events are only double buffered). If the frame rate is significantly faster than the time step, the fixed time step schedule will sometimes not run, completely missing the input (which will no longer be just-pressed).

### Duplicated inputs

If the fixed timestep is *faster* than the frame rate, fixed time step systems sometimes need to run catch-up, and are evaluated multiple times in the same frame. However, this will cause `just_pressed` (or `just_released`) to be registered as true multiple times (as `Input` will not update between these system evaluations.

This can cause extremely confusing behavior. Note that, unlike missed inputs, events should not be affected by this failure mode, due to the internal cursor stored in `EventReader`.

## Proposed fix

We should have a default fixed time step system set (see the stageless RFC). Input updating (and input event clearing) should occur in there, rather than as part of the main schedule.

Gameplay systems should effectively always be run in the fixed time step: only rendering-related code should be processed each frame.

Ping @maniwani for thoughts.

**Comment by maniwani** [comment]
Right, so the ideal situation is we can read from a buffer of timestamped input events (or state). Then in each iteration of the fixed timestep, we'd just yield the input that happened within that slice of time. 

That's currently blocked on `winit` and `gilrs`. `gilrs` actually does timestamp its events, but using the wrong clock (`SystemTime`).

> Input updating (and input event clearing) should occur in there, rather than as part of the main schedule.

So in lieu of handling it perfectly, yeah I agree that the next best thing would be to refresh events multiple times. That said, we might want to sample in both places, once in each timestep iteration and again when we get to `PreUpdate`.

---

Even once we have buffered, timestamped inputs, we probably still want the capability to peek ahead (observe inputs that arrived in the current frame) midway for XR things.

**Comment by alice-i-cecile** [comment]
Should be solved as part of #5984.

**Comment by jabuwu** [comment]
> Gameplay systems should effectively always be run in the fixed time step: only rendering-related code should be processed each frame.

The impact of this statement is fairly substantial isn't it? The problem is moved from fixed updates to frame updates, and I think many newcomers to Bevy aren't even considering fixed updates. Suddenly it becomes mandatory, or potentially houses very tricky frame rate dependent bugs.

The default fixed timestep period is 1/60th of a second so it will seemingly be working properly in frame updates for anyone with a 60hz vsync app.

**Comment by dubrowgn** [comment]
I've been struggling with this for a while as well, and from a consumer perspective, what I really want is a way to get all the input events "since the last time I asked". In that context, the lifetime of the events is well defined, and no guesswork is needed. Just dispose of the events after they have been consumed.

This is different from the current implementation of "since the last rendered frame", but this is also potentially different from "since the last fixed update" as currently defined by bevy because there are valid reasons for rolling your own fixed update logic. For example, in some lockstep network models, the next "fixed update" can't happen until all client inputs are received. Or, you might want to enforce a fixed update time budget to keep the program interactive under load. Or, you might want to run the simulation at some multiple of real time. Etc. Etc.

In a typical evented architecture, consumers register for the events they are interested in. Just spit balling here, but maybe something similar could work here:

```rust
app.register_event_stream::<Input>(tag_name);

...

sys_handle_input(input_stream: ResMut<EventStream<Input>, With<tag_name>>) {
    input_stream.poll();
    for event in input_stream.drain() {
        ...
    }

    // or

    for event in input_stream.consume_new() {
        ...
    }
}
```

Conceptually, bevy would tee all the `Input` events into registered `EventStream`s of matching type, so if multiple consumers needed to handle `Input` events they wouldn't stomp on each other. The current events are effectively global, which makes them more difficult to reason about. With something like `EventStream`, each consumer effectively gets their own event queue, so they don't have to worry about what other systems are or aren't doing with the global events.

Something like this could theoretically be implemented fairly cheaply with one event queue, and a set of start and end "pointers" for each registered consumer. When a consumer polls, you check for new events, and move the consumer's end "pointer" to the end of the queue. When a consumer consumes, the consumer's start "pointer" moves forward until it reaches the corresponding end "pointer". When all start "pointers" have moved passed an event, drop it from the event queue.

**Comment by dubrowgn** [comment]
> If you're several seconds worth of steps behind, you're in a death spiral or you have like 0.5 FPS.

This is true with the current Bevy implementation, but it is not a characteristic of _all_ implementations of a fixed update loop. This is why I mentioned there are alternative implementations.

It seems like we are talking past each other a bit here. Part of that is definitely my fault, since I jumped to potential implementation details before aligning on requirements. I don't mean to argue, but I do hope to get across my original point so that it is considered in whatever eventual solution that is reached: A solution that is directly coupled to the Bevy implementation of a fixed update loop is only useful in that specific context.

Alternative implementations of a fixed update loop would continue to have all the same input event problems seen today. But, when the events API is defined in terms of (for example) "since I last asked", the question of update cadence doesn't even arise. This means such a solution (or some similar solution) would be flexible enough to be used in any implementation of a fixed update loop (or even _any_ update loop). For example:

> What I'm trying to get at is "fixed update" and "frame update" will read the same input events, just independently. Each frame will see the events captured during the previous frame. Each simulation step will see the events captured "during" the previous step.

This sounds great! As long as "during the previous step" isn't directly coupled to Bevy's fixed update implementation. Instead (again, as an example), you could expose an API that allows you to get events between given start and end timestamps. That kind of API could be used in any update loop strategy. If you want to process all of the new events, you can do that. If you want to process only new events from a specific slice of time, you can do that too. You can even do a combination of both in any combination of loops with different cadences to handle different kinds of inputs, all without Bevy having to know anything about how your loops actually work.

**Comment by richardhozak** [comment]
For those that run into this, and are using `Res<Input<KeyCode>>` in their fixed update systems, you will still get missed inputs, the solution is to use events in fixed update as fixed in this PR. If you want to use `Input<KeyCode>` you can use local system param (`Local<Input<KeyCode>>`) and feed it events, like so:

```rust
fn handle_input(
    mut keys: Local<Input<KeyCode>>,
    mut keyboard_input_events: EventReader<KeyboardInput>,
) {
    keys.clear();
    for event in keyboard_input_events.read() {
        if let Some(key_code) = event.key_code {
            match event.state {
                ButtonState::Pressed => keys.press(key_code),
                ButtonState::Released => keys.release(key_code),
            }
        }
    }

    // do something with inputs

    let up = keys.pressed(KeyCode::Up);
    let down = keys.pressed(KeyCode::Down);
    let left = keys.pressed(KeyCode::Left);
    let right = keys.pressed(KeyCode::Right);
    let respawn = keys.just_pressed(KeyCode::Return);
}
```

**Comment by alice-i-cecile** [comment]
I've chewed on this a bit, and I think I'd actually like to handle this a lot like how `Time` works upstream in Bevy.

There's no *canonical* location for when to update the just_pressed information: both update and fixed update are defensible. And some games might even want to do *both*.

So instead, swap the behavior of `just_pressed` based on which schedule we're in. Provide some fallback methods to opt out of this behavior, but make the obvious thing to do just work using the same pattern.

We'll probably need to implement this by keeping track of its pressed state in both the main and fixed schedule.

**Comment by Henrique194** [comment]
Any updates on this issue?

**Comment by alice-i-cecile** [comment]
We've worked to improve event handling in fixed updates, per #10077 and #13808.

Over at leafwing-input-manager, we've also tackled this problem via a (not yet released) state-switching solution in https://github.com/Leafwing-Studios/leafwing-input-manager/pull/522 by @cBournhonesque. While that is slated for upstreaming, we should consider implementing a parallel solution for `ButtonInput` for those who want to operate on raw inputs.

**Comment by dubrowgn** [comment]
I'm revisiting this because it's bit me again recently. https://github.com/bevyengine/bevy/pull/10077 kind of works around the worst of it. but it fails when you can't use bevy's `FixedUpdate`. You can work around that by re-implementing `TimePlugin`, but it's less than ideal. Abstractly, a schedule agnostic solution should be possible, and would neatly sidestep a lot of weirdness.

At a fundamental level, there is a bi-directional relationship between the event list and the event cursors. The cursors need to reference the event list to do anything useful, and the event list needs to iterate all the cursors to safely garbage collect consumed events. In any other language, this relationship would be trivial to implement, but I'm struggling to get it done in rust/bevy.

One possibility I've been playing around with is keeping a list of cursor positions in `Events`, and changing cursors to simply hold a "subscriber id" which can be used to index into the cursor list. Very roughly:

```rust
type EventSubscriberId = usize;

struct EventCursor<E> {
    sub_id: EventSubscriberId,
}

struct Events<E> {
    // circular buffer of events; front is oldest
    events: VecDeque<E>,
    // event Id associated with `events[0]`
    base_event_id: usize,
    // positions of all subscribed cursors
    cursors: Vec<AtomicUsize>,
}

impl Events<E> {
    // subscribe a new cursor
    fn subscribe(&mut self) -> EventCursor<E> {
        self.cursors.push(AtomicUsize::new(self.base_event_id));
        EventCursor<E> { sub_id: self.cursors.len() - 1 }
    }

    fn read(&self, sub_id: EventSubscriberId) -> EventMutIteratorWithId<E> {
        let event_id = self.cursors[sub_id].load(Ordering::Relaxed);
        let delta = event_id - self.base_event_id;
        self.events.iter().skip(delta).map(|event| {
            let instance = EventInstance { event_id, event };
            event_id += 1;
            self.cursors[sub_id].store(event_id, Ordering::Relaxed)
            instance
        }
    }

    // clean up events that have been processed by all subscribers
    fn gc_processed_events(&mut self) {
        let min_event_id = self.cursors.iter()
            .map(|event_id| event_id.load(Ordering::Relaxed))
            .min();

        match min_event_id {
            // no subscribers? gc all events to prevent leaks
            None => self.events.clear(),
            Some(event_id) => {
                let delta = event_id - self.base_event_id;
                // VecDeque::truncate_front is not stable at time of writing:
                // https://github.com/rust-lang/rust/issues/140667
                self.events.rotate_left(delta);
                self.events.truncate(self.events.len() - delta);
            },
        }
    }
}
```

There are a couple issues with this though:
1. Rust can't express each cursor only ever writing to their own slot in `Events.cursors`, so I used `AtomicUsize` as an escape hatch.
2. The real issue is life cycle management of the cursors. You can potentially use `FromWorld` to create them by looking up `Events<E>` where `E` matches the cursor type you are trying to create. However, I can't find a good way to clean them up. Implementing `Drop` can't access the associated `Events<E>` or `World` because we are using opaque handles to break the bi-directional references. `SystemParam` seems to suffer from the same deficiency (no reciprocal to `init_state()`.

Anyway, maybe this will spark some ideas, or maybe someone who knows more about this stuff can point out something I'm missing.

**Comment by dubrowgn** [comment]
I just ran into a new version of this (for me at least) where events are dropped depending on how long a state transition takes.

1. System `A` publishes Event `e`
2. State transition begins, pending data load from disk
3. System `B` only runs after state transition, and wants to consume `e`
4. Several update cycles go by
5. Event `e` dropped
6. Transition completes
7. System `B` never sees Event `e`

This makes event handling with state transitions inherently racy because loading time is heavily device dependent. I don't see how you can address this using the current double-buffer approach because you don't know how long to wait before purging the event buffers.

**Comment by Shatur** [comment]
One possible solution is to do something similar to what we did for events: https://github.com/bevyengine/bevy/pull/10077
