### ISSUE TITLE
Lighting of GLTF models with negative scale is inverted

### ISSUE THREAD

**Issue by adamwych** [bevyengine/bevy#7901]
**Update**
https://github.com/bevyengine/bevy/issues/7901#issuecomment-1454984501

## Bevy version

0.9.1 / `main` branch at `f87de368436a1a65aecb8e0088d93244dd5a467c`

## Relevant system information

```ignore
AdapterInfo { name: "NVIDIA GeForce GTX 1080 Ti", vendor: 4318, device: 6918, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "528.49", backend: Vulkan }
```

## What you did

I made a model in Blender, exported it to GLTF and imported it inside my Bevy application using `SceneBundle`:

```rust
let box_dude = assets.load("box_dude.glb#Scene0");

commands.spawn(SceneBundle {
    scene: box_dude,
    ..default()
});

commands.spawn(Camera3dBundle {
    transform: Transform::from_xyz(12.0, 36.0, 12.0).looking_at(Vec3::ZERO, Vec3::Y),
    ..default()
});

commands.spawn(PointLightBundle {
    transform: Transform::from_xyz(4.0, 2.0, 4.0),
    point_light: PointLight {
        color: Color::WHITE,
        shadows_enabled: true,
        ..Default::default()
    },
    ..Default::default()
});
```

## What went wrong

Outside faces of `box_dude` are not lit up:
![image](https://user-images.githubusercontent.com/6526954/222934971-e21eaf40-ab1d-4268-85be-5de13c8b8827.png)

If you zoom in, you can see that the *edge* of the face is kinda lit up, but I guess this is just some bleeding due to the camera being far away and it's actually the inside that's lit up.

If I move the `box_dude` to be inside the point light, you can see that his head's outside faces are lit up, which is incorrect.
![image](https://user-images.githubusercontent.com/6526954/222934994-990bfd1b-a207-4703-b710-7352c3b13a52.png)

**I tried flipping the normals and re-exporting, but it does not change anything.**

The same file looks correct in online GLTF viewers:
![image](https://user-images.githubusercontent.com/6526954/222935145-5b2e0ea7-cf33-4d3e-b9d8-07958829274c.png)

## Additional information

Here's the `.glb` file I used:
https://www80.zippyshare.com/v/4UrsUvvL/file.html

**Comment by james7132** [comment]
Just to be sure, can you reproduce this on `main`? 0.10 is just about to release.

**Comment by adamwych** [comment]
Update:
I fixed it using https://www.gltfeditor.com/ to flip the normals instead of Blender:
![image](https://user-images.githubusercontent.com/6526954/222935849-613e407e-42f3-45ef-8a3f-bcb02136a961.png)

I guess Blender is not flipping the normals correctly for some reason...

**Comment by adamwych** [comment]
@james7132 Also happens in 0.10:
![image](https://user-images.githubusercontent.com/6526954/222939359-bf142005-bb98-4ba9-aefa-c2c1991d84c5.png)

**Comment by adamwych** [comment]
**Update 2:**
Using "Apply Transform" on the entire object in Blender fixes the issue.

I did some experiments and figured out that while modeling, I must have mirrored everything at some point. Blender implements mirroring by simply setting the scale to the negative of whatever it currently is and that's where the issue was - the scale of my model was negative so my lighting was "negative" too.

![image](https://user-images.githubusercontent.com/6526954/222941009-f4cda769-fe0e-4e20-a2f0-d6a5324c149b.png)

I understand the issue now, but maybe there should be some mechanism in place in Bevy to fix those kinds of models during import? Other apps didn't have such problem with this file and it might be very confusing to someone in the future.

**Comment by janhohenheim** [comment]
I can confirm that this still happens on 0.10, since I just spent a while debugging it :/

**Comment by devil-ira** [comment]
Perhaps setting [`double_sided`](https://docs.rs/bevy/latest/bevy/pbr/struct.StandardMaterial.html#structfield.double_sided) to true on the material would fix it.
Not really sure why we don't enable it by default.
